# Generated by Django 5.2.4 on 2025-07-08 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=60)),
                ('presentacion', models.CharField(max_length=50)),
                ('precio', models.FloatField()),
            ],
        ),
    ]
